spring.application.name=backend

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/ascending_cloud_staffing?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Vishishta1501@

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=false